ALTER TABLE "Note" ADD COLUMN "tags" TEXT NOT NULL DEFAULT '';

CREATE TABLE "Pair" (
  "id" SERIAL NOT NULL,
  "code" TEXT NOT NULL,
  "userId1" BIGINT NOT NULL,
  "userId2" BIGINT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Pair_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Pair_code_key" ON "Pair"("code");
ALTER TABLE "Pair" ADD CONSTRAINT "Pair_userId1_fkey" FOREIGN KEY ("userId1") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Pair" ADD CONSTRAINT "Pair_userId2_fkey" FOREIGN KEY ("userId2") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
