ALTER TABLE "User" ADD COLUMN "notifyEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyUtcHour" INTEGER NOT NULL DEFAULT 19;
ALTER TABLE "User" ADD COLUMN "notifyTzOffset" INTEGER NOT NULL DEFAULT 2;
